### ISSUE TITLE
Sta ti je sa Facebook-om?

### ISSUE THREAD

**Issue by 44gala** [MilosMisic/Spring-MVC-Demo#1]
Ne mogu ti poslati poruku...kao da si me blokirao?

**Comment by MilosMisic** [comment]
Ugasih. Smara me.

**Comment by 44gala** [comment]
Brz si, dosao ti mail?

Daj nemoj mi to raditi koga sada da smaram na Facebook-u? :P

**Comment by MilosMisic** [comment]
pisi mi na milosmisicbg@gmail.com a ovo ovde izbrisi sve

**Comment by 44gala** [comment]
Vazi
